### ISSUE TITLE
Setting default homeserver when using static files?

### ISSUE THREAD

**Issue by wagner-intevation** [Awesome-Technologies/synapse-admin#284]
Is there any way to set a default homeserver, when using the installation variant 1 ("[Download the tarball and serve with any webserver](https://github.com/Awesome-Technologies/synapse-admin#steps-for-1)")?

I already tried adding `REACT_APP_SERVER` to the arrary in `synapse-admin/static/js/main.73885304.chunk.js` which also defines the `PUBLIC_URL`, but that has no effect.

**Comment by awesome-michael** [comment]
By now there is no option to set a default homeserver for the installation.

**Comment by efelon** [comment]
@wagner-intevation Maybe change the issue title also to "default homeserver".

This would be really great, because when you self host synapse and synapse admin, most of the time (if not even always) you are using it only with your local server. This would save some typing effort on every login. And might even help to disclose the URL to the admin API?!

**Comment by efelon** [comment]
Docker is no option for me. I hope some more people also find this option useful and give their thumbs up.

**Comment by wagner-intevation** [comment]
> Docker is no option for me.

I used Docker only for building the app. Instead you can also use these commands directly on your host machine:
```
yarn --network-timeout=100000 install
RUN PUBLIC_URL=$PUBLIC_URL REACT_APP_SERVER=$REACT_APP_SERVER yarn build
```
See Dockerfile

**Comment by MajliTech** [comment]
I made a handful Jupyter notebook to build static website with custom homeserver set.
Run online: https://colab.research.google.com/drive/18oo2M_4ke7ktO2rjwcOBWFyo5iNYLiks?usp=sharing (yes, I know, a gist soon to follow...)
