### ISSUE TITLE
how to modify REACT_APP_SERVER arg after build synapse-admin on docker

### ISSUE THREAD

**Issue by odroid382** [Awesome-Technologies/synapse-admin#486]
hi, 

I build synapse-admin on docker with REACT_APP_SERVER arg in the docker-compose.yaml but i put "" around the value and I don't find how to modify it now ?
I try rebuild but the bad value stay in the login panel without possibility to change it :-(

thanks

**Comment by sebix** [comment]
Why not re-build it again?

You can also remove the additional quotes or change the domain name from the generated code.

**Comment by awesome-manuel** [comment]
> > Why not re-build it again?
> > You can also manually remove the additional quotes or change the domain name from the generated code.
> 
> No one wants to waste their time building an image, it defeats the entire purpose of configurable template images. Deployment with environmental variables (such as through Compose) just needs to work. I manually overwrote the entrypoint to force an environmental variable into the nginx launch and it still wouldn't use the env set. The implementation is broken.

This is due to the fact that synapse-admin is a SPA. It is assembled and minified during build into static HTML and Javascript. The server will just deliver that static content but cannot modify it.

I agree that it would be nice to be able to modify some values in the final container and we have such functionality in the pipeline. It's just not that simple to implement.
